config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  	member do
  		post 'confirm'
  	end
  end
  
  root to: 'treehouses#index'
  
  devise_for :users,
  	controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 


  get '/mytrees', to: "treehouses#mytrees"
  get '/search', to: "treehouses#search"
  resources :treehouses, only: [:index, :show, :new, :create, :edit, :update, :destroy], :path => "/"



  mount Attachinary::Engine => "/attachinary"
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  belongs_to :treehouse
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, :class_name => 'User'
  belongs_to :treehouse

  validates :start_date,:end_date, :guest_count, presence: true
  # validates :start_date, :end_date, uniquness: true


end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :treehouse
  belongs_to :space_type
end

app/models/space_type.rb
class SpaceType < ApplicationRecord
	has_many :spaces
end

app/models/treehouse.rb
class Treehouse < ApplicationRecord
  belongs_to :owner, :class_name => 'User'
  has_many :bookings, dependent: :destroy

  has_many :amenities
  has_many :spaces
  has_attachments :photos, maximum: 2

	validates :name, :category, :capacity, :bed_count, :tree_type, :description, :rate, :address, :photos, presence: true
  # validates :name, :category, :capacity, :bed_count, :location, :tree_type, :description, :photos, presence: true
  # validates :name, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def banner_image
    if photos.size > 0
      photos.first.path
    else
      'https://unsplash.it/1280/500'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :bookings, dependent: :destroy, :foreign_key => 'renter_id'
  has_many :treehouses, :foreign_key => 'owner_id'

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  # validates :first_name, :last_name, :phone_number, :birth_date, :contact, :terms_of_service, presence: true
  # # :email, :encrypted_password, 
  # # validates :encrypted_password, length: { minimum: 6 }

  # # validates :email, uniqueness: true
  # # validates :email, format: { with: /\A.*@.*\.com\z/ }

  # validates_acceptance_of :terms_of_service, acceptance: true, :message => "must be abided"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
  class BookingsController < ApplicationController
  def index
    @rent_bookings = Booking.where(renter_id: current_user.id)
    @own_bookings = Treehouse.where(owner_id: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def confirm
    @booking = Booking.new(booking_params)
    @booking.renter = current_user

  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end

  end

  def edit
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:state, :renter_id, :treehouse_id, :start_date, :end_date, :price, :guest_count)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/treehouses_controller.rb
class TreehousesController < ApplicationController

  layout "search", only: [ :search ]
  # skip_before_action :authenticate_user!, only: :home

  # skip_before_filter :verify_authenticity_token 
  # skip_before_filter :authenticate_user!, only: [ :home ], raise: false

  skip_before_action :authenticate_user!, only: [:index, :show, :search]



  def index
  	@treehouses = Treehouse.all
    @mapped_treehouses = Treehouse.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@mapped_treehouses) do |treehouse, marker|
      marker.lat treehouse.latitude
      marker.lng treehouse.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def search
    @address = params["treehouse"]["address"]

    # if there's an address...
    @treehouses = @address ? Treehouse.near(@address, 50) : Treehouse.all
    # @treehouses = Treehouse.near(@address, 50) if @address

    # if the address results return 0 results
    if @treehouses.length == 0
      @treehouses = Treehouse.all
      @empty_results = true
    end
    # @treehouses = @treehouses.length == 0 ? Treehouse.all : @treehouses 

    @treehouses.limit(20)
    # @treehouses = Treehouse.all
    @mapped_treehouses = @treehouses.select { |t| !t.latitude.nil? && !t.longitude.nil? }

    @hash = Gmaps4rails.build_markers(@mapped_treehouses) do |treehouse, marker|
      marker.lat treehouse.latitude
      marker.lng treehouse.longitude
      # marker.infowindow treehouse.name
      marker.infowindow render_to_string(partial: "/treehouses/map_box", locals: { treehouse: treehouse })




       # {
       #        "lat": <%= @treehouse.latitude %>,
       #        "lng": <%= @treehouse.longitude %>,
       #        "infowindow": "<p><%= @treehouse.name %></p><img src='<%= cl_image_path @treehouse.photos.first.path %>' height='200'></p>"
       #      }
    end
  end


  def show
  	@treehouse = Treehouse.find(params[:id])
    @booking = Booking.new
    # @alert_message = "You are viewing #{@treehouse.name}"
    @treehouse_coordinates = { lat: @treehouse.latitude, lng: @treehouse.longitude }

  end


  def new
  	@treehouse = Treehouse.new
  end

  def create
  	@treehouse = Treehouse.new(treehouse_params)
  	@treehouse.owner = current_user
  	if @treehouse.save
  		redirect_to treehouse_path(@treehouse)
  	else
  		render :new
  	end
  end


  def edit
    @treehouse = Treehouse.find(params[:id])
  end

  def update
  	@treehouse = Treehouse.find(params[:id])
    @treehouse.update(treehouse_params)
  	if @treehouse.save
  		redirect_to treehouse_path(@treehouse)
  	else
  		render :new
  	end
  end

  def destroy
  	@treehouse = Treehouse.find(params[:id])
  	@treehouse.destroy
  	redirect_to treehouses_path
  end

  def mytrees
    @owned_trees = Treehouse.where(owner_id: current_user.id)
  end

  def treehouse_params
  params.require(:treehouse).permit(:name, :description, :category, :capacity, :bed_count, :address, :zip_code, :city, :country, :tree_type, :rate, photos: [])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/treehouses_helper.rb
module TreehousesHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for @booking, url: confirm_booking_path, method: 'post' do |f| %>
<%= f.input :start_date, label: "Check In",placeholder: "8/03/2017" %>
<%= f.input :end_date, label: "Check Out",placeholder: "8/15/2017" %>	
<%= f.input :guest_count, :collection => (1...16), selected: 1 %>	
<%= f.hidden_field :treehouse_id, value: @treehouse.id %>	
<div class="text-center">
	<%= f.submit class: 'btn btn-light full-width', value: "Book now" %>	
</div>
<% end %>

app/views/bookings/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3">
			<div class="form-formats">
				<h1>Confirm your booking for <%= @booking.treehouse.name %></h1>
				<p><strong>Check In:</strong> <%= @booking.start_date %></p>
				<p><strong>Check Out:</strong> <%= @booking.end_date %></p>
				<!-- PUT THE PRICE HERE -->
				<%= simple_form_for @booking do |f| %>
				<%= f.input :guest_count, :collection => (1...16), selected: 1, label: "Who's coming? (Number of guests)" %>	
				<%= f.hidden_field :start_date, label: "Check In" %>
				<%= f.hidden_field :end_date, label: "Check Out" %>	
				<%= f.hidden_field :renter_id %>	
				<%= f.hidden_field :treehouse_id %>	
				<%= f.submit value: "Confirm booking", class: "btn btn-light margin20 full-width" %>	
				<% end %>		
			</div>
		</div>
	</div>
</div>


<!-- put all attributes that belong to booking inside the form (hidden)
 -->

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">

<!-- 	<div class="row">
		<div class="col-xs-12 text-right margin40">
			<h4 class="bookings-welcomemsg"><i class="fa fa-tree"></i> Welcome <%= current_user.first_name %> </h4>
		</div>
	</div> -->

	<div class="row">
		<div class="col-xs-12 text-center margin60">
			<h2 class="h2-reg">Your rental bookings</h2>
		</div>
	</div>

<% @rent_bookings.each do |booking| %>
	<div class="row margin40 padded40 border-top">
		<div class="col-xs-6">
			<%= link_to treehouse_path(booking.treehouse) do %>
				<%= cl_image_tag booking.treehouse.photos.first.path, class: "img-responsive", width: 500, height: 250, crop: :fill %> 
			<% end %>
		</div>
		<div class="col-xs-6 booking-info">
			<h3 class="margin0"><%= booking.treehouse.name %></h3>
					<p><strong>Check In:</strong> <%= booking.start_date %></p>
					<p><strong>Check Out:</strong> <%= booking.end_date %></p>
					<p><%= link_to "Cancel booking", booking_path(booking), method: :delete, class: "cancel-link"  %></p>
		</div>
	</div>
<% end %>

</div>



<div class="container">

	<div class="row">
		<div class="col-xs-12 text-center margin100">
			<h2 class="h2-reg">Your owner bookings</h2>
		</div>
	</div>

<% @own_bookings.each do |treehouse| %>
<%	treehouse.bookings.each do |booking| %>
	<div class="row margin40 padded40 border-top">
		<div class="col-xs-6">
		<%= link_to treehouse_path(treehouse) do %>
			<%= cl_image_tag booking.treehouse.photos.first.path, class: "img-responsive", width: 500, height: 250, crop: :fill %> 
		<% end %>
		</div>
		<div class="col-xs-6 booking-info">
			<h3 class="margin0"><%= booking.treehouse.name %></h3>
					<p><strong>Check In:</strong> <%= booking.start_date %></p>
					<p><strong>Check Out:</strong> <%= booking.end_date %></p>
			<h4>Renter info</h4>
				<p><strong>Name:</strong> <%= booking.renter.first_name %> <%= booking.renter.last_name %></p> 
				<p><strong>Email:</strong> <%= booking.renter.email %></p> 
					<p><%= link_to "Cancel booking", booking_path(booking), method: :delete, class: "cancel-link" %></p>
		</div>
	</div>
<% end %>
<% end %>

</div>




<!-- 

<div class="container">

	<div class="row">
		<div class="col-xs-12 text-right">
			<h2 class="h2-reg">Your owned treehouses</h2>
		</div>
	</div>

<% @rent_bookings.each do |booking| %>
	<div class="row margin40 padded40 border-top">
		<div class="col-xs-6">
			<%= cl_image_tag booking.treehouse.photos.first.path, class: "img-responsive", width: 500, height: 250, crop: :fill %> 
		</div>
		<div class="col-xs-6">
			<h3><%= booking.treehouse.name %></h3>
					<p><strong>Check In:</strong> <%= booking.start_date %></p>
					<p><strong>Check Out:</strong> <%= booking.end_date %></p>
					<p><%= link_to "Cancel booking", booking_path(booking), method: :delete %></p>
		</div>
	</div>
<% end %>

</div>
 -->

<!-- 

<div class="container">
	<div class="row">
		<div class="col-xs-12 margin20"><h4><i class="fa fa-tree"></i> Welcome <%= current_user.first_name %> </h4>
			<h2 class="h2-reg">Your rental bookings</h2>
		</div>

		<div class="col-xs-12 col-sm-6">
			<div class="margin20">
			<% @rent_bookings.each do |booking| %>
				<%= cl_image_tag booking.treehouse.photos.first.path, class: "img-responsive", width: "500" %> 
			<% end %>
			</div>


			
		</div>
		<div class="col-xs-12 col-sm-6">
			
				<% @rent_bookings.each do |booking| %>
				<div>
					<h3><%= booking.treehouse.name %></h3>
					<p><strong>Check In:</strong> <%= booking.start_date %></p>
					<p><strong>Check Out:</strong> <%= booking.end_date %></p>
					<p><%= link_to "Cancel booking", booking_path(booking), method: :delete %></p>
				</div>
				<% end %>

			
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h2 class="h2-reg">Your owner bookings</h2>
		</div>
	</div>

	<div class="row">



		<div class="col-xs-12 col-sm-6">
			<div class="margin20">
			<% @rent_bookings.each do |booking| %>
				<%= cl_image_tag booking.treehouse.photos.first.path, class: "img-responsive", width: 500, height: 164, crop: :fill %>
			<% end %>
			</div>
		</div>


		<div class="col-xs-12 col-sm-6">
	
				<% @own_bookings.each do |treehouse| %>

					<%	treehouse.bookings.each do |booking| %>
						<p><strong>Name:</strong> <%= booking.treehouse.name%></p>
						<h3>START: <%= booking.start_date %></h3>
						<h3>END: <%= booking.end_date %></h3>
						<h3>RENTER: <%= booking.renter.email %></h3>

						<p><%= link_to "Cancel booking", booking_path(booking), method: :delete %></p>
					<% end %>
				
					<h3>All i own: <%= treehouse.name %></h3>
						
				<% end %>

			
		</div>
	</div>
</div> -->

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-4">
				<div class="footer-col">
					<h3>About TreeHousing</h3>
					<p class="tagline">Live in a treehouse.
					</p>
					<p>
						We are a community of treehouse lovers.  We believe that everyone should have an opportunity to live in a treehouse.
					</p>
				</div>
			</div>
			<div class="col-xs-12 col-sm-4">
				<div class="footer-col">
					<h3>Navigate</h3>
					<ul class="menu">
						<li><%= link_to "Home", treehouses_path %></li>
						<li><%= link_to "Search", search_path %></li>
						<li><%= link_to "List A Treehouse", new_treehouse_path %></li>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
						<li><%= link_to "Login", new_user_session_path %></li>
					</ul>
				</div>			
			</div>
			<div class="col-xs-12 col-sm-4">
				<div class="footer-col">
					<h3>Let's get social</h3>
					<ul class="social list-inline">
						<li><a href="#""><i class="fa fa-facebook"></i></a></li>
						<li><a href="#""><i class="fa fa-twitter"></i></a></li>
						<li><a href="#""><i class="fa fa-heart"></i></a></li>
					</ul>
				</div>			
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 text-center">
			<div class="copyright">
				© TreeHousing 2016 <i class="fa fa-heart"></i></a>
			</div>
			</div>
		</div>



	</div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
 <!--    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
<!-- 
      <a class="navbar-wagon-item navbar-wagon-link" href="#">Help</a> -->
    

      <!-- Notification -->
   <!--    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
         <!--  <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %> -->
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <!--    <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to mytrees_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My Treehouses") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>


    <%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <a class="navbar-wagon-item navbar-wagon-link" href="#">Help</a>




    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>





       

    <!-- Button (call-to-action) -->
<!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>

            <li><%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li><%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
        <% else %>
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>

            <li><%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            
              <!-- Login text link -->
            <li>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li><%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

        <% end %>


      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_fixed.html.erb
<div class="navbar-wagon" style="position:fixed; top: 0; width: 100%; z-index: 500;">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
 <!--    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
<!-- 
      <a class="navbar-wagon-item navbar-wagon-link" href="#">Help</a> -->
    

      <!-- Notification -->
   <!--    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
         <!--  <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %> -->
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <!--    <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to mytrees_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My Treehouses") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>


    <%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <a class="navbar-wagon-item navbar-wagon-link" href="#">Help</a>




    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>





       

    <!-- Button (call-to-action) -->
<!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>

            <li><%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li><%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
        <% else %>
            <li>
              <%= link_to treehouses_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>

            <li><%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            
              <!-- Login text link -->
            <li>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

            <li><%= link_to "List Treehouse", new_treehouse_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

        <% end %>


      </ul>
    </div>
  </div>
</div>